// Copyright (c) 2018, J. Salvador Arias <jsalarias@csnat.unt.edu.ar>
// All rights reserved.
// Distributed under BSD2 license that can be found in the LICENSE file.

package parsimony

import (
	"math/rand"
	"sort"
	"strings"
	"testing"

	"github.com/js-arias/ramita/matrix"
)

// Benchmark for a Wagner tree
func BenchmarkWagner(b *testing.B) {
	r := strings.NewReader(largeBlob)
	s := matrix.NewScanner(r)
	m, _ := NewMatrix(s)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		m.Wagner()
	}
}

// Benchmark for a Wagner tree without storing
// previous state copies.
func BenchmarkWagnerNoCopy(b *testing.B) {
	r := strings.NewReader(largeBlob)
	s := matrix.NewScanner(r)
	m, _ := NewMatrix(s)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		m.noCopyWagner()
	}
}

// Benchmark for a Wagner tree without bounding
// the search (but with previous state copying)
func BenchmarkWagnerUnbound(b *testing.B) {
	r := strings.NewReader(largeBlob)
	s := matrix.NewScanner(r)
	m, _ := NewMatrix(s)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		m.unboundWagner()
	}
}

// Becnhmark for a Dayoff swapping with
// a new node order each time the swapping is made.
func BenchmarkDayoff(b *testing.B) {
	r := strings.NewReader(largeBlob)
	s := matrix.NewScanner(r)
	m, _ := NewMatrix(s)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		tr := m.Wagner()
		tr.Dayoff()
	}
}

// Becnhmark for a Dayoff swapping with the same
// node order.
func BenchmarkDayoffJustOne(b *testing.B) {
	r := strings.NewReader(largeBlob)
	s := matrix.NewScanner(r)
	m, _ := NewMatrix(s)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		tr := m.Wagner()
		tr.dayoffJustOne()
	}
}

// NoCopyWagner returns a new tree,
// build with the Wagner algorithm and
// a random addition sequence.
func (m *Matrix) noCopyWagner() *Tree {
	// randomize terminal order
	terms := make(map[int]*Terminal, len(m.Names)-1)
	var ls []int
	for _, t := range m.Names {
		if t == m.Out {
			continue
		}
		v := rand.Int()
		ls = append(ls, v)
		terms[v] = t
	}
	sort.Ints(ls)

	// Add the firts three terminals
	tr := &Tree{}
	root := &Node{
		Chars: make([]uint8, len(m.Out.Chars)),
	}
	tr.Root = root
	tr.Nodes = append(tr.Nodes, root)
	out := &Node{
		Anc:   root,
		Term:  m.Out,
		Chars: m.Out.Chars,
	}
	tr.Nodes = append(tr.Nodes, out)
	n0 := &Node{
		Anc:   root,
		Chars: make([]uint8, len(m.Out.Chars)),
	}
	tr.Nodes = append(tr.Nodes, n0)
	root.Left = out
	root.Right = n0

	tm := terms[ls[0]]
	t0 := &Node{
		Anc:   n0,
		Term:  tm,
		Chars: tm.Chars,
	}
	tr.Nodes = append(tr.Nodes, t0)
	tm = terms[ls[1]]
	t1 := &Node{
		Anc:   n0,
		Term:  tm,
		Chars: tm.Chars,
	}
	tr.Nodes = append(tr.Nodes, t1)
	n0.Left = t0
	n0.Right = t1
	increDown(n0)

	// add the remaning terminals
	for _, i := range ls[2:] {
		tr.noCopyAddTerm(terms[i])
	}

	return tr
}

// NoCopyAddTerm adds a new terminal to the tree.
func (tr *Tree) noCopyAddTerm(tm *Terminal) {
	na := &Node{
		Chars: make([]uint8, len(tm.Chars)),
	}
	nt := &Node{
		Anc:   na,
		Term:  tm,
		Chars: tm.Chars,
	}
	na.Left = nt

	var bestPos *Node
	bestCost := tr.Cost() + len(tm.Chars)*2
	for _, d := range tr.Nodes[2:] {
		// Test the position
		a := d.Anc
		na.Anc = a
		na.Right = d
		d.Anc = na
		if a.Left == d {
			a.Left = na
		} else {
			a.Right = na
		}

		cost := increDown(na)
		if cost < bestCost {
			bestCost = cost
			bestPos = d
		}

		// Restore the position
		if a.Left == na {
			a.Left = d
		} else {
			a.Right = d
		}
		d.Anc = a
		increDown(na)
	}

	// Add the nodes
	a := bestPos.Anc
	na.Anc = a
	na.Right = bestPos
	bestPos.Anc = na
	if a.Left == bestPos {
		a.Left = na
	} else {
		a.Right = na
	}
	increDown(na)
	tr.Nodes = append(tr.Nodes, na, nt)
}

// UnboundWagner returns a new tree,
// build with the Wagner algorithm and
// a random addition sequence.
func (m *Matrix) unboundWagner() *Tree {
	// randomize terminal order
	terms := make(map[int]*Terminal, len(m.Names)-1)
	var ls []int
	for _, t := range m.Names {
		if t == m.Out {
			continue
		}
		v := rand.Int()
		ls = append(ls, v)
		terms[v] = t
	}
	sort.Ints(ls)

	// Add the firts three terminals
	tr := &Tree{}
	root := &Node{
		Chars:     make([]uint8, len(m.Out.Chars)),
		charsCopy: make([]uint8, len(m.Out.Chars)),
	}
	tr.Root = root
	tr.Nodes = append(tr.Nodes, root)
	out := &Node{
		Anc:   root,
		Term:  m.Out,
		Chars: m.Out.Chars,
	}
	tr.Nodes = append(tr.Nodes, out)
	n0 := &Node{
		Anc:       root,
		Chars:     make([]uint8, len(m.Out.Chars)),
		charsCopy: make([]uint8, len(m.Out.Chars)),
	}
	tr.Nodes = append(tr.Nodes, n0)
	root.Left = out
	root.Right = n0

	tm := terms[ls[0]]
	t0 := &Node{
		Anc:   n0,
		Term:  tm,
		Chars: tm.Chars,
	}
	tr.Nodes = append(tr.Nodes, t0)
	tm = terms[ls[1]]
	t1 := &Node{
		Anc:   n0,
		Term:  tm,
		Chars: tm.Chars,
	}
	tr.Nodes = append(tr.Nodes, t1)
	n0.Left = t0
	n0.Right = t1
	increDown(n0)

	// make the copy of assignations and costs
	for _, n := range tr.Nodes {
		if n.Term != nil {
			continue
		}
		copy(n.charsCopy, n.Chars)
		n.costCopy = n.Cost
	}

	// add the remaning terminals
	for _, i := range ls[2:] {
		tr.unboundAddTerm(terms[i])
	}

	return tr
}

// UnboundAddTerm adds a new terminal to the tree.
func (tr *Tree) unboundAddTerm(tm *Terminal) {
	na := &Node{
		Chars:     make([]uint8, len(tm.Chars)),
		charsCopy: make([]uint8, len(tm.Chars)),
	}
	nt := &Node{
		Anc:   na,
		Term:  tm,
		Chars: tm.Chars,
	}
	na.Left = nt

	var bestPos *Node
	bestCost := tr.Cost() + len(tm.Chars)*2
	for _, d := range tr.Nodes[2:] {
		// Test the position
		a := d.Anc
		na.Anc = a
		na.Right = d
		d.Anc = na
		if a.Left == d {
			a.Left = na
		} else {
			a.Right = na
		}

		cost := increDown(na)
		if cost < bestCost {
			bestCost = cost
			bestPos = d
		}

		// Restore the position
		if a.Left == na {
			a.Left = d
		} else {
			a.Right = d
		}
		d.Anc = a

		// Restore the assignations
		for a != nil {
			copy(a.Chars, a.charsCopy)
			a.Cost = a.costCopy
			a = a.Anc
		}
	}

	// Add the nodes
	a := bestPos.Anc
	na.Anc = a
	na.Right = bestPos
	bestPos.Anc = na
	if a.Left == bestPos {
		a.Left = na
	} else {
		a.Right = na
	}
	increDown(na)

	// Set assignations
	for x := na; x != nil; x = x.Anc {
		copy(x.charsCopy, x.Chars)
		x.costCopy = x.Cost
	}
	tr.Nodes = append(tr.Nodes, na, nt)
}

func (tr *Tree) dayoffJustOne() {
	// randomize node order
	nodes := make(map[int]*Node, len(tr.Nodes))
	ls := make([]int, 0, len(tr.Nodes))
	for _, n := range tr.Nodes {
		copy(n.charsCopy, n.Chars)
		n.costCopy = n.Cost
		if n == tr.Root {
			continue
		}
		v := rand.Int()
		ls = append(ls, v)
		nodes[v] = n
	}
	sort.Ints(ls)
	for improve := true; improve; {
		improve = tr.swapOneTime(nodes, ls)
	}
}

// Swap test a node position among all
// nodes in the indicated node set.
// It returns true if a new position is found.
func (tr *Tree) swapOneTime(nodes map[int]*Node, ls []int) bool {
	bestCost := tr.Cost()
	for _, i := range ls {
		// removes the node
		n := nodes[i]
		if n.Anc == tr.Root {
			continue
		}

		a := n.Anc
		sis := a.Left
		if sis == n {
			sis = a.Right
		}
		a.Left = n
		a.Right = nil

		gf := a.Anc
		unc := gf.Left
		if unc == a {
			unc = gf.Right
		}
		gf.Left = unc
		gf.Right = sis
		a.Anc = nil
		sis.Anc = gf

		increDown(gf)
		for x := gf; x != nil; x = x.Anc {
			copy(x.charsCopy, x.Chars)
			x.costCopy = x.Cost
		}

		// test positions of the node
		for _, j := range ls {
			p := nodes[j]
			if p.IsDesc(a) {
				continue
			}
			if p == sis {
				continue
			}
			if p.Anc == tr.Root {
				continue
			}

			pa := p.Anc
			psis := pa.Left
			if psis == p {
				psis = pa.Right
			}
			pa.Left = psis
			pa.Right = a
			p.Anc = a
			a.Right = p
			a.Anc = pa

			cost, stop := increBound(a, bestCost)
			if cost < bestCost {
				// The new position is the best
				// so update backups and return
				for x := a; x != nil; x = x.Anc {
					copy(x.charsCopy, x.Chars)
					x.costCopy = x.Cost
				}
				return true
			}

			// restore positions
			p.Anc = pa
			pa.Right = p
			a.Anc = nil
			a.Right = nil

			// Restore assignations
			for x := p; x != nil; x = x.Anc {
				copy(x.Chars, x.charsCopy)
				x.Cost = x.costCopy
				if x == stop {
					break
				}
			}
		}

		// restore the node
		sis.Anc = a
		a.Right = sis
		a.Anc = gf
		gf.Left = unc
		gf.Right = a
		copy(a.Chars, a.charsCopy)
		a.Cost = a.costCopy
		increDown(gf)
		for x := gf; x != nil; x = x.Anc {
			copy(x.charsCopy, x.Chars)
			x.costCopy = x.Cost
		}
	}
	return false
}

var largeBlob = `
> dna
PORI_Scypha_ciliata                      ?AACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAT-AAGCG-TTCTTATACTGTG-AAACTGCGAAT-GGCTCA-TTA-AATCAG-TTATAG-TTTATT-TGAT-G-TTGACT----TACT------------ACTTGGA-TAACCG-TGG-TAATTCTAGAGCTAATA-CATGC---GTTAAA--GTCCT---GACCTCT---------------------CGGGGAAGGGAT-----GTATTTATTAG-ATCCAAAACCGA---TGCAG--TCGAAA----------------------------------GGCT--GGTT-----ATTGG-TGA---TTCATGATAA-CTGA------ACGG?-TCGCA-----TGGT-CTT-------GC-GCC-GGCGA----TGACTCATAC-AAATATCTGCCCTATCA-ACTTT-CGATGGTAAGGTAGTG-G-CTTACCAT----GGTTG--CAACGGG-TAACGGAGAA-TTA-G?GTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-AATCCCGACACGGGGAGGTAGTGA-CGATAAATAACAATGCAGGA--CTCT-AAC-----G-AGTCTTGCAATTGGAATGAGA-ACAAT---TTAAAC-CCC-TTAACGAG-GAACAATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTT--CGGAGCGGAGCTCACG-------GTCCGCCTTTTCGGGTGTGCACTGTGCTG---------------------------------------------------------------------------TTCTGTTCTTCTTCTCGTGGAG-CGTGTGT-GCTCTTCAT-TGAGTGTGCACGTAACTCGGG--------------------------------------------------------------------------------------------ACTTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGCC-----------TT-GGCTTGAA-T?CATTAGCATGGAATAATGAAATAGGACTT-TGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC--C--AAGGTAATGAC?AATAGGGACAGT-T-GGGGG-CATTCG---TAT-TCAATTGTCAGAGGTGAAATTCTTGGATTTAT-GGAAG--ACGAA-CAACTGCGAAAG-CA---TTTGCCAAGGAT--GTTTT-CATTAATCAAGAACGAAAGTTGGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCCAACCATAAACGATGCC-GACTAGGGAT-CGGTGGATGTTA-TTA---AAT------GACTCC--ATCGGCACCT----TATGAGAAATCA--AAGTTTTTG-GGTTCCGGGGGGAGTATAATCGCAAGATC-GGAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCAGGT-CC-AGAC-ATAGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCT-ATGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGTTAACG-AACGAGACCTT--AACCTGCTAAA-TAGT-TAC--GCGATTCTC--------------------------------------------------------------------------------------------------------------------------------------------------------------GAATCGCGGCC-AACTTCTTAGAGGGACTAT-TGGT-GTT-----------TA-ACCG-ATG-GAAGTTTGAGGCAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCCGCACGCGCGC-TACACTGATGAAGTCAG---CGAGTTC-------TTCCTTCACCG--ATA-GG-TGT--GGGTAATC-TT----GTGA--AAC-TTCATCGTGCTGGGGAT-AGACC-AT-TGCAATTATTGGTC-TTCAACGAGGAATTCCTAGTAAGCGCAAGT-CATCAGCTTGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATCTTCGGATTGC-TGGCCCGGCGGCCTTGT--------------------------------------------GTTGCCGGACACAGCGAG---AAGTTGATCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCAGAAGGATCAA???
ANNE_Clit_Enchytraeus_sp                 ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGCAC-AGACC---TTTACACGGTG-AAGCTGCGAAT-GGCTCA-TTA-GGCCAC-CCATGA-TTTATT-AGATTG-TACAA-----TCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AAGCAA--GCTCC---GACCCCGTCTTCACG------------GCGGGGAAAGAGC-----GCGTTTATTAG-ATCAAA-ACCAAT--CGGGG--CCTCGG-----------------------------------TTC--CGTACG---TTCGG-TGA---CTCTGGATAA-CTTCGA----GCTGA-TCGCA-----CGGC-CTC-------GA-GCC-GGCGA----CGTATCTTTC-AAGTGTGTGCCCTATCA-ACTGT-CGATGGTAAGTGATAT-G-CTTACCAT----GGTGG--TAACGGG-TAACGGGGAA-TCA-GGGCT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGATTCGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTC-ATTCG----A-GGCCCCGTAATTGGAATGAGA-ACACT---TTAAAT-CCT-TTAACGAG-GATCCATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTCCAGGCTGGCG-------GTTCGTTTCGCGACGA-TACTGCCCGTCCTG-------------------------------------------------------------------------ACCTACCTGCCGGTCGT----C-TCGTCGT-GCTCTTCAT-TGAGTGCGTCGAGTGGCTGG--------------------------------------------------------------------------------------------AACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCA----------GTC-TGCCTGAA-TAACCGCGCGTAGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TT--GAGGTAATGATTAAGAGGGACAGA-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGTC-GACTAGCGAT-CCGCGATCGTTG-TTCA--TAT------GACCTC--GCGGGCAGCC----TTCGGGAAACCA--AAGTTTTTG-GATTCCGGAGGAAGTATAGTTGCAAAGCC-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTTG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GAT-TGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGT-TCG--CCGATTGCCTAATCT----------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGCGTT-AACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GTCA-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTTCTTCTT----CCTGATCCG--TAA-GG-ACC--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGCAATTTTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGGATGGTTTA-GTGAGATCCTCGGATTGG-ACTCGAGTCGGTGGGCA-------------------------------------------ACCGTCGACTCGGTGCTCTAAGGAGACGATCAAACTTGA-----------TCATCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
ANNE_Clit_Hirudo_medicinalis             ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGCTCATACCT----TTACACGGTG-AAGCTGCGAAT-GGCTCA-TTAAGGCCAC-CCATGAATTTATTAAGATCG-TACTA-----TTCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATAACATGC---AACCAA--GCTCT---GACCCGCG----------------------AGGGAGGAGC-----GCGTTTATTAAGATCAAA-ACCAAT--CGGTT--CTTCGTCTC-----------------TTCCGCGGGGACGGAGGC--CGTAAC---GATGG-TGA-CTCTGTGGATAA-CTTCGG----GCGGA-TCGCA-----TGAC-CTC-------GA-GTC-GGCGA----CAGATGTTTC-AAGTGTGTGCCCTATCA-ACTTT-CGATGGTACGCGACTT-G-CCTACCAT----GGTAG-TTAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCAACTCAGGGAGGTAGTGA-CGAAAAATAACGATACGAGGGACTC-TCAT-----A-GGCCGCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCAATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTTCGGACTGGTTGCAA---CCTCGCG-----------------------------------------------------------------------------------------------GCGTAGCGACCC---------------------------------------GCTCCGACCTGTTTTCGGTTCTGCGCCC--GGTTCTTCTTAACC-GAGTG-----C--CGGG-TGC--GGCC---GA---------------------------GACGTTTACTTTG-AAAAAATTAGAGTGCTTAAAGCAGGCT---------CGAC-AGCCTGAA-TAGTAGCGCATGGAATAATAGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAGC-TC--GAGGTAATGATTAAGAGGGACAGT-T-GGGGT-CATTGCGGTTATTTCGATTGTCAGAGGTGAAATTCTTGGATTTGC-GAAAG--ACGAA-CTAATGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGTC-GACTAGCGAT-CCGCGGGA-GTT-GATCG-TAC------GACCCC--GCGGGCAGCC----TCCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGGAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGT-CC-GGAC-ACCGGAAGGATTGACAGA-TTGATAGC-----TCTTTCTTAATTCG-GTGGGT-GGTGGTGCATGGCCGTTTCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCTTCATCCTGCTAAA-TAGT-ACA--GCCGCTGTC----------------------------------AGCCGCAACGTCTTCGGGCGTTCGGACGTCTGGAAACAGCG-----------------------------------------------------------------------------------CTGCCGGTGCA-GACTTCTTAGAGGGATGCG-TGGC-GTT-----------TA-GTCA-CAC-GAGA-TTGAG-CAATAACAGGTC-GTGAT-GCCCTTA-GA-TGTTCGGGGGCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTTTTTCGTG---CCTGCTCCG--CGA-GG-AGT--GGGTAACC-CG----TTGA--AAC-TCCTTCGTGCTAGGGAT-TGGGG-TT-TGTAATTATTCCCCCATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGGATGGTTTA-GTGAGGTCATCGGATCGA-AGGCTCGGCGGGGCTTGG-------------------------------------------CCTTGCGCGATTCTTTGAG-AAGACGA-TCGAACTTGA-----------TCATCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
ANNE_Poly_Nereis_virens                  ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACT--TTTGACACAGTG-AAACTGCGAAT-GGCTCA-TTA-AATCAG-TCCAGG-TTCCTT-AGATCG-TATTA-----TCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---ATTCAA--GCTCC---GACCTTTC-----------------------GGGAAGAGC-----GCGTTTATTAG-ATCAAA-ACCAAT--CGGGTTT-------------------------------------------CACGACCCGCCTGTTGG-TGA---CTCTGGATAA-CCTTGA----GCTGA-TCGCA-----TGGC-CTC-------GG-GCC-GGCGA----CGGATCTTTC-AAGTGTCTGCCCTATCA-ACTTT-CGATGGTACGTGAACCTG-CCTACCAT----GGTTG-TTAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGTCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTCAATCG-----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCCATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CTGGTCCAGGCTCG-------CGGTTG-----------------------------------------------------------------------------------------------CCTCGCGGCGTTACTGCCCGTCCTGACCTACCAACCGGTTTCCCTTGGTGCTCTTTACTGAGTGCTTC--------------------------------------------------------------------------------GGGTGGCCGGAACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCA----------TTT-CGCCTGAA-TAGTGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----CCGGAAC-TC--GAGGCAATGATTAATAGGGACGGC-C-GGGGG-CATTCG---TAT-TACGGTGT-AGAGGTGAAATTCTTGGATCCGCCGTAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CCTAGTTCTGACCATAAACGATGCC-GACTAGCGAT-CCGCGGGA-GTT-GTTTTCAT-------GACCCC--GCGGGCAGCC----TTCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCA-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGCAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTATTAAA-TAGT-TCG--CCGATAGC-------------------------------------------------------------------------------------------------------------------------------------------------------------AATCTGTCGGCGC-AACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GCCA-CGC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGTTTGT-----CCTGATCCG--CAA-GG-ACC--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGCAATTATTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATCCTCGGATGGG-TCCCGGCGTGGT-------------------------------------------GGGCAACCATCGGGTCGGAGTCCCGAGAAGACGATCAAACTTGA-----------TCATCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
ANNE_Poly_Ridgeia_piscesae               ????CT-GGTTGAT?CTGCCAGTAGTTATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACC---TCGACACGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCGG-TCACTC-TTTATT-GGATCG-ATCA------TCCT------------ACTTGGA-TAACTG-TAG-TAATTCTAGAGCTAATA-CATGC---AAA-TC--GGTCC---GACCGC?C--------------------GACGGGAAGAAC-----GCTTTTATTAG-ATCAAA-ACCAAT--CGGTC--CGTCGTTC---------------------------CGCGGCGGGC-CGTCCG---ATTGG-TGA---CTCTGGATAA-CTTTGG----GCTGA-TCGCA-----TGGC-CTC-------GA-GCC-GGCGA----CGTATCTTTC-AAGTGTCCGCCCTATCA-ACTTT-CGATGGTACGTGATAT-G-CCTACCAC----GGTCG--TAACGGG-TAGCGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGCT-CTC-TTTCG----A-GGCTCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-TATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--GGGGTCCAGGCTGGCG-------GT?C--------------------------------------------------------------------------------------------------GCCGCGCGGCGGT---------TACTGCTC---------GTCCT--GACCTACCTGCCGGTGTCGTC----------GC--GGATGCTCTTCGCC-GAGTG-----T--CTCG-GGT--GGCC---GG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGCG---------CGCT-CGCCTGAA-TAATGTTGCATGGAATGATGGAATAGGACCT-CGGT-TCTA-GTTTG---TTGGTTT----TCGGAAC-TC--GAGGTAATGATTGAGAGGGACGGA-C-GGGGG-CATTCG---TAT-TACGGCGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGAA-CTACAGCGAAAG-CA---TTTGCCAAGAAC--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGCTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGTC-GATTAGCGAT-CCGCCGGT-GTT-GTTTC-CAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAATCTTTG-GATTCCGGGGGAAGTATGGTTGCAAATCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGC?-TGC-GCTTAATTTGACTCAACACGGGAAAACT-CACCCGGA-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGTT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTATTAAA-TAGT-CCG--?TCGTTCCTTCG------------------------------------------------------------------------------------------------------------------------------------------------------------A?CGCGCGCC-GACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GCCA--AC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGTTCGC-----CCTGGTCCG--GAA-GG-ATC--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTCTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAACGGTTTA-GTGAGGCCCTCGGATTGG--ACCCGGCACTCCGGCGGGC----------------------------------AACCGTCG?ACCGGTGGGCCGGGAAG----ACGG-CCGAACTTGA-----------CCGTTTAGAGGTCGTAAAAGT-CGTAACAAGGTTTC?GTAGGTGAACCTGC?GAAGGATCATTA?
ARTH_Chel_Aphonopelma_sp                 ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATGCC---TCCTTAAGGCG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACCT-----TACT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---ATCAGA--GCTCC---GACCC----------------------TCTGGGGACGAGC-----GCTTTTATTAG-ACCAAA-ACCAAT--CGGAC--TCG---------------------------------------TTC-CGTATCC--CATGG-TGA---CTCTGTATAA-CTTTGG----GCTGA-TCGCA-----CGGG-CTT-------GT-CCC-GGCGA----CGCATCTTTC-AAGTGTCTGCCTTATCA-ACTGT-CGATGGTAGGCTTATGCG-CCTACCAT----GGTC---TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGCAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTCTTTT-G----A-GACCCCGTAATTGGAATGAGT-ACACT---CTAAAT-CCT-TTAAC-AG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCGGTTAAAAAGCTCGTAGTTGGATCT--CAGTTCCAGACGGGCG-------GTCCGCCTAAC--GGTG-GTTACTGCCT-------------------------------------------------------------------------GGCCTGAACAGCCCAGCCGGTTTC-CCTAGAT-GATCTTCAC-CGGTTGTCCTGGGTGACCGGC---------------------------------------------------------------------------------------------ACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCG----------TGT-AGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACTT-CGTT-TCTA-TTTTG---TTGGTTT----TCGGAAT-AC--GAGGTAATGATTAAGAGGGACAGA-C-GGGGG-CATTCG---TAT-TGCGACGCTAGAGGTGAAATTCTTGGACCGTC-GCAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCC-AACCAGCGAT-CCGCCTGAGTTC-CTCA--AAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTGTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAACCT-TACCCGGC-CC-GGAC-ACTGGAAGGATTGACAGA-TTAAGAGC-----TCTTTCTTGATTCA-GTGGGT-GGTGGTGCATGGCCGT-TCATAGTT-GGT-GGAGC-GATTTGTCTGGTTTATTCCGATAACG-AACGAGACTCT--AGCCTACTAAA-TAGG-CGTC-CCGATCACTTCT-------------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGGCG--TTCTTCTTAGAGGGACAAA-TGGC-GTT-----------TA-GCCG-CAC-GAGA-CAGAG-CAATAACAGGTCTGAGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGCTTTC-----CCTGTCCGG---TA-GG-ACT--GGGTAACC-CG----TTCA--ACC-TCCTTCGTGATAGGGAT-AGGGG-CT-TGTAATTGTTCCCC-TTGAACGAGGAATTCCCAGTAAGCACGAGT-CATAAGCTCGTGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTCGGATTGG--CGCTCGGAGCGGCCGCA-----------------------------------AGGTCGCGCCGGCGT-GCCGGAAAGCG----ATTGACCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATC?????
ARTH_Chil_Scolopendra_cingulata          ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTGC-ATACC---GCATTAAGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACCA-----CCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AGAAAA--GCTCC---GACCTTC-----------------------GGGGACGAGC-----GCTTTTATTAG-AACAAG-ACCAAT-ACGGAT--CGGCAG----------------------------------CGGTC-CGTTCCCG-TTTGG-TGA---CTCTGGATAA-CTTGGA----GCCG?-TCGCA-----CGGT-CCT------CGT-ACC-GCCGA----CCCATCTTTC-AAATGTCTGCCTTAT?A-ACTGT-CGAT?GTAGGTTATGC-?-C?TACCAT----GGTCG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCACGCAAATTACCC-ACTCCCGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTCTT-CCG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCG--TAATTCCAGC-TCCAATAGCGTATATTAA-GTTGTTGCG-TTAAAAAGCTCGTAGTTGGATCT--CGGTGCCGGTCCGCGG-------GTCCGCCTCGCGCGTCT-CACTGCCGGCCCCGGAGCCA-----------------------------------------------------------------TCCTGCCGGCCG-----TCCC----TCGGT-GCTCTTTAT-TGAGTGTCTTGGGTGACCGGA---------------------------------------------------------------------------------------------ACGTTTACTTTG-AACAAATTAGAGTGCTCCAAGCAGGCG--------TGCTC-CGCCCGCA-TAGCCCAGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTT??---T?G?TTT----TCGGAAC-CG--GAGGTAATGATTAATAGGGACAGA-C-GGGGG-CATTCG---TAT-TGCGACGC?AGAGGTGAAATTCTTGGACCGTC-GCAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCC-AACCAGCGAT-CCGCCGGAGTTC-CTCC--GAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTGTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACCGGAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTACTAAA-TAGA-CGT--CCGATCCTGGGGTGCCGGTGCCTCCTAA-ACCTCCGCTCTTTCGAAAAGAGTGGGAGGCGGGGGAACGGCTTTGCCTCT------------------------------------------------------------------------------------------GTCGGACGATTGCTTCTTAGAGGGACAAG-CGGC-GCT-----------CA-GCCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-G??GCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGT?CTCC----CCTAGTCCG--GAA-GG-ACC--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGATAGGGAT-CGGGG-CT-TGGAATTGTTCCCC-GTGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTCGGACTGG--CGGTCGCTGCGGCCCT--------------------------------------CGGGTCGCGGTGGCGTGCCGGGAAG-----ATGACCGAACTTGA-----------CCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATC----?
ARTH_Hexa_Tenebrio_molitor               ?TCCCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTCAGTAC-AAGCC---GAATTAAGGTG-AAACCGCGAAA-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACCCAC---ATTT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AAACAGA-GCTCC---AACCGGAA---------------------ACGGAAGGAGC-----GCTTTTATTAG-ATCAAA-ACCAAT--CGGTG--GCGGT-------------------------------CTCCGTCAT-CGTACAA--CTTGG-TGA---CTCTGAATAA-CTTTAC----GCTGA-TCGCA-----CGGT-CTT-------GC-ACC-GGCGA----CGCATCTTTC-AAATGTCTGCCTTATCA-ACTGT-CGATGGTAGGTTCTGC-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCGGCACGGGGAGGTAGTGA-CGAAAAATAACGATACGGGA--CTCAT-CCG----A-GGCCCCGTAATCGGAATGAGT-ACACT---CTAAAC-CCT-TTAACGAG-GATCAATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCGGTTAAAAAGCTCGTAGTCGAATCT--GTGTCCCGCGCCGCCG-------GTTCATCGTTCG-CGGTGTTAACTGG---------------CGT----------------------GCC-GCGGGACGTCCTGCCGGT------------GGGCTTAG---------CTCGT--GA-GGGCG--GCCCAACTCAA-TCCCGCCGC-----GG-TGCTCTTCGTT-GAGTG------T-CGA--GGTGGGCC----GG--------------------------------------------------CACGTTTACTTTG-AACAAATTAGAGTGCTTAAAGCAGGC------TAAAACTT-CGCCTGAATACTGTGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAATTTT--GAGGTAATGATTAATAGGAACGGA-T-GGGGG-CATTCG---TAT-TGCGACGTTAGAGGTGAAATTCTTGGATCGTC-GCAAG--ACGGA-CAGAAGCGAAAG-CA---TTTGCCAAAAAC--GCTTT-CATTGATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCC-AGCTAGCGAT-C-CGCCGACGTT-CCTCC-GAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAGCTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAACCT-CACCAGGC-CC-GGAC-ACCGGAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGG-CGT--ATTTCGACATCCCAAAGGCCCGCTGGTC-CCGGGTT--------------CGC-TCGGTGACCGTGCGCGGTTTTTACT------------------------------------------------------------------------------------GTCGGCGTACAAACAATTCTTCTTAGAGGGACAGG-CGGC-TTC-----------TA-GCCG-AAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCCGCACGCGCGC-TACACTGAAGGAATCA----GCGTGTCCTC------CCTGGCCGA--GC--GG-CCC--GGGTAACC-CG----CTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGCAATTGTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTCGGACCGG--TACGCGGTGGCGTTTC---------------------------------------GGCGTCGCCGATGTTGCTGGGAAG-----ATGACCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
ARTH_Mala_Panulirus_argus                ????CT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTGTAAGTAC-AGGCC---GACTTAAGGCG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-CTATGA-TTCATT-GGATCTGTAAACCC---ACTT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---ACCACG--TCTCT---GACCGC-----------------------AAGGGAAGAGC-----GCTTTTATTAG-TTCAAA-ATCAGT--CGGGC--CTCGGTC--------------------------------CGTTAC-CCATG----TGTGG-TGA---ATCTGAATAA-CTTCTC----GCTGA-GCGCA-----GGGT-CTC------CGC-ACC-GGCGC----CGCATCTTTC-AAGTGTCTGCCTTATCA-GCTTT-CGATTGTAGGTTATGC-G-CCTACAAT----GGCTA--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCTAA-GGAAGGCAGCAGGCACGCAAATTACCC-ACTCCCGGCACGGGGAGGTAGTGA-CGAAAAATAACGATGCGAGA--CTCAT-CCG----A-GGCCTCGCAATCGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCCATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGTGTATATTAAAGTTGTTGCGGTTAAAAAGCTCGTAGTTGGATTT--CAGTTCCGGAGTGACG-------GTTCACCCCCCGGTGCCTACTCTCACGCTCCGAA--------------------------------------------------------------------CAGCCGCACCCCGCCCGGTTGC-ACGGGGT-GTCTT-CAT-CGAGTGTCCCGAGTGGCCGGC----------------------------------------------------------------------------------------------ACGTTTACTTTG-AAAAAATTAGAGTGCTCAGAGCAGGC-----TGTTTGAAT-GGCTTGAA-TGTCTATGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-CC--GAGGTAATGACTAATAGGAACAGG-C-GGGGG-CATTCG---TAT-TGCGACGCTAGAGGTGAAATTCTTGGACCGTC-GCAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGGAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCT-GACTAGCGAT-CCGCCGGCGTTA-TTCC--CAT------GACCCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTCTTTG-AGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGAAATCT-CACCCGGC-CC-GGAC-ACCGGAAGGATTGACAGA-TTGAGAGC-----TCTTTCTCGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCTGATAACG-AACGAGACTCT--AGCCTATTAAC-TAGT-CGA--CGGATCTCCAGCATGCTCCGTGGT--------------------------------------------------------------------------------------------------------------------------------------------GTCCAGTACGCAAC-TTCTTCTTAGAGGGATAAG-CGGC-AATTC---------TA-GCCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCCGCACGCGCGC-TACACTGAAGGGACCAA---CGTGTTGTCCC-----CCT--CCGA--GA--GG-AGC--GGGTAACC-CG----TTCA--AAC-CCCTTCATGATAGGGAT-TGGGG-CT-TGCAATTGTTTCCC-ATGAACGAGGAATTCCCAGTAAGCGCAAGT-CATTAGCTTGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGG-CTTCGGACCGG--CGCTCTTGGATGTTGTACCCCTCCCCCGCAAGGGTGCTT---------GGAGGTGTTCTCGCCTGGAGCTGACGGAAAG-----ATGTCCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCATAGGTGAACCTGCGGAAGGATCATTA?
BRAC_Terebratalia_transversa             ??????-????????????????AGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ACACT---TTCACACGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACAA-----TCCT------------ACTTGGA-TAACTG-TAG-TAATTCTAGAGCTAATA-CATGC---AAACAA--GCTCC---GACCT-----------------------CGCGGGAAGAGC-----GCTTTTATTAG-ATCAAG-ACCAAT--CGGCT--CGC---------------------------------------CCC-CGTCCA---ATTGG-TGA---CTCTGGATAA-CTTTGG----GCTGA-TCGCA-----TGGC-CTT-------GC-GCC-GGCGA----CGTATCTTTC-AAATGTCTGCCCTATCA-ACTTT-CGATGGTACGTGACAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACTTCTAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTCTTT-CG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTTTAGGCTGGCG-------GTCC--GCTCGCGCGTCA--CTGCCCGTCC--------------------------------------------------------------------------TGACCTACCTCCCGGTTTT---C--------------------------------------------------CCTT--GG-TGCTCTTGACT-GAGTG-----T--CTCG-GGT--GGCC---GG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCG----------ACT-CGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TT--GAGGTAATGATTAATAGGGACGGC-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGGA-CAGCTGCGAAA?-CG---TTTGCCAAGAGC--GTTTT-CATTAGTCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CCTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-TCGCCGGAGTTG-CTTC--AAT------GACTCG--GCGAGCAGCT----TCCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TTCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGTTAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGACTGGTTAATTCCGATAACG-AA?GAGACTCT--AGCCTATTAAA-TAGT-TCA--CCGATATCGATCA------------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGTGCC-AACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GCCA--AC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAA---CGTGTGTCTGC-----CCTGGTCCG--ACA-GG--??--GGGTAACC-CG----GTGA--ACC-TCCTTCGTGCTAGGGGT-TGGGG-CT-TGTAATTCTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGTGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATAATCGGACTGG-TCCGGCG---CGGGGT-----------------------------------------TCGCCTCGCGCGGTGTCACCGGG--AAGACGATCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTT-----------------------------?
BRYO_Plumatella_repens                   ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACC---TCGAGACGGTG-AAACCGCGAAT-GGCTCA-TTA-TATCAG-TCACGA-TTCATT-AGATCG-TACAA-----TCCT------------ACTTGGA-TAACTG-CGT-TAATTCTGGAGCTAATA-CATGC---AAC-GA--ACTCC---GACCTTCG----------------------GGGGAAGAGC-----GCTTTTATTAG-ATCAAA-ACCAAT--CGGGG--CA-----------------------------------------AC-CGTACAGT-TTTGG-TGA---CTCTGGATAA-CTTTGG----GCTGA-TCGCA-----TGGC-CTT------CGA-GCC-GGCGA----CGTATCCTTC-AAATGTCTGCCCTATCA-ACTTT-CGATGGTACGTGATAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGAT-CTC-TATCG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCCATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGCTGCGGTTAAAAAGCTCGTAGTTGGATCT--CAGTTACGGGCAGGTG-------GTTC--------------------------------------------------------------------------------------------------ACCTCACGGTGC----------TACTACCTG--------GACCG--GACCTATTGCT--GGTTCCTC---------TGA--GG-TGCCCTTCATT-GGGTG-----C--CCCA-GGA--GACC---AG---------------------------AGCGTTTACTTTG-AAAAAATTGGAGTGTTCAAAGCAGGCG---------AATT-CGCCTGAA-CAGTCGTGCATGGAATAATGGAAAAGGGCCT-CGGT-GCTA-TTTTG---TTGGTTC----TCGGTAC-TC--GAGGTAATGGTTGAAAGGGACAGA-C-GGGGG-CATTCG---TAT-TGCGACGTTAGAGGTGAAATTCTTAGATCGTC-GCAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTGACCTTAAACGATGCC-AACTGGCGAT-CCGCGGGG-?TT-?CTTC-AAT------GACTCG--GCTGGCAGCT----TCCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGATAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGT-TCA--CCGATCTCC------------------------------------------------------------------------------------------------------------------------------------------------------------GACGGTCGGGCTG-GACTTCTTAGAGGGACAAG-CGGT-GTT-----------TA-GTCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGCATCAG---CGTGTCCTAC------CCTGGTCCG--ACA-GG-ATC--GGGTAACC-CG----ATGA--ACC-GCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTATTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCAAGT-CACTAGCTTGCGTT-GATTACGTCCCTGCCCTTGGTACACACCGC-C-GTCGCTAC-TACCGATTGAGTGGTTTA-GTGAG-CCCTCGGACTGG--TCTCGGGCCGGGAGCCTT--------------------------------------TCATCGAGCGGTGTGCCGGAAAG----ACGG-TCAAACTTGC-----------TCACTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
CHOR_Branchiostoma_floridae              ???CCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAC--GTGCAAGTTT-AAACT-----GTCTCAGTG-AAACTGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-TGATCG-TCACA-----TCCT------------ACATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGCG--GAAGAA--GCGCC---GACCTCA----------------------CGGTCTGGCGT-----GCATTTATCAG-ACCAAG-ACCAAC--CCGGG--GTTCG-----------------------------------CCCC--GGTCCC---TTTGG-TGA---CTCTGGATAA-CCCA------GCCGA-TCGCA-----CGGT-CTT------CGC-ACC-GGCGA----CAGATCATTC-GAATGTCTGCCCTATCA-ACTTT-CGATGGTAGGTTCTGT-G-CCTACCAT----GGTGG--CAACGGG-TGACGGGGAA-TCA-GGGTT-CG-GTTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCGACTCGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTCTTT-CG----A-GGCCCCGTAATTGGAATGGGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCGGTTAAAAAGCTCGTAGTTGGATCT--TGGGACCGGGCTTGCG-------GTCCGCCGCGAG-GCGTGTCACTGCTCGTCCCGG-------------------------------------------------------------------CCTCCCC----GCCGGA---TTCT-CCTTGGT-GCTCTTAAC-TGAGTGCCTCGGGGTGCCGG---------------------------------------------------------------------------------------------AGCGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGCC----------TGG-CGCCTGAA-TAGTGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTCG---TTGGTTT----TCGGAAC-GT--GAGGTAATGATCAAGAGGGACGGA-C-GGGGG-CATTCG---TAT-TGCGGCGGGAGAGGTGAAATTCTTGGATCGCC-GCAAG--ACGAA-CCACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTGATCAAGAACGAAAGTTGTGGGCGCGAAGGCGATC-AGATACCGC--CCTAGTCACAACCATAAACGATGCC-AACCAGCGAT-CCGCCGGCGTTA-CTTC--GAT------GACCCG--ATGGGCAGCT----CCCGGGAAACCT--GAGTTTTCG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GGAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGGAAACT-CACCCGGC-CC-GGAC-ACAGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCT-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGCTAATCCCGATAACG-AACGAGACTCT--GGCATGCTAAC-TAGT-TGC-GGCGATCCCGCGCGA------------------------------------------------------------------------------------------------------------------------------------------------------------TCGGCCGC-AACTTCTTAGAGGGACAGC-CGGC-AGT-----------AA-GCCG-GAC-GAGA-TGGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACAATGAAGGCATCAG---CGAGTCTT-----TCGCCTTCGCCG--AAA-GG-TGC--GGGTAACC-TG----CTGA--ACC-GCCTTCGTGCTAGGGAT-CGGGG-AT-TGCAATTATCTCCC-ATGAACGAGGAATTCCCAGTAGATGCGTGT-CATCAGCGCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGGTCAGTCGATCGG-CCCCTCTCGGGCCGGCA-------------------------------------------ACGGTCTGGAGGAGCGCCG-AGAAGCCGATCAAACTTGA-----------CCATTTAGAGGAAGTAAAAGT-CGT????????????????????????????????????????
CNID_Tripedalia_cystophora               ??????-??????????????GTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAT-AAGCA---CTTGTACTGTG-AAACTGCGAAT-GGCTCA-TTA-AATCAG-TTATCG-TTTACT-TGATCG-TAT-------CCTT------------ACATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---GAA--A--ATCCC---GACCTCT------------------------GGAAGGGAT-----GTATTTATTAG-ACTAAAAGCCAAT--ACCGG--TTT----------------------------------CGCGACC--GGTTCT---ATTGG-TGA---TTCATGATAA-CTTC------TCGAA-TCGCA-----CGGG-CTT-------GT-ACC-GGCGA----TGTTTCATTC-AAATATCTGCCCTATCA-ACTGT-CGATGGTAAGGTAGTG-G-CTTACCAT----GGTTG--CAACGGG-TAACGGAGAA-TTA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAT-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-AATCCTGACACAGGGAGGTAGTGA-CAAGAACTAACAATATGGGG--CCTTT--C-----T-GGTCTCATAATTGGAATGAGT-ACAAT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTT--CGGGTTGGAGTTGACG-------GTCT--------------------------------------------------------------------------------------------------GCCGCAAGGTATG--------TTACTGTCC---------ACTCT---GTCCTT---CTTCGCAA-G-GACT--TCA-----CA-TATCCTTAACT-GGCTG---T--G-TGTA-GGA--TTT----GC---------------------------GACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAAGC---------ATACT-AGCTTGAA-TACATGAGCATGGAATAATGGAACAGGACTT-CGGT-CCCG-TTTTG---TTGGTTT----CCAGGAC--C--GACGTAATGATTAAGAGGGACAAT-T-GGGGG-CATTCG---TAT-TTCGTTGTCAGAGGTGAAATTCTTGGATTTAC-GAAAG--ACGAA-CAACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGATCGAAGACGATC-AGATACCGT--CCTAGTTCTAACCATAAACGATGCC-GACTAGGGAT-CAGCGGGC-GTT-ATTG--TAT------GACCCC--GTTGGCACCT----TATGGGAAACCC--AAGTTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAACCT-CACCAGGT-CC-AGAC-ATAGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATCCT-ATGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGTTAACG-AACGAGACCTT--AACCTGCTAAA-TAGT-TAC--GCGATTC--------------------------------------------------------------------------------------------------------------------------------------------------------------TTGAATCGTGGTT-AACTTCTTAGAGGGACTAT-TGGT-GTT-----------TA-ACCA-AAG-TCA--GGAAGGCAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCCGCACGCGCGC-TACACTGACGATGGTAG---CGAGTC------TGACCCTTCACCGG-AAG-G--TGT--GGGTAATC-TT----TTGA--AAC-ATCGTCGTGATGGGGAT-AGATC-AT-TGCAATTATTGATC-TTGAACGAGGAATTCCTAGTAAGCGCGAGT-CATCAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGGAATCCGGATTGG-CAGCCCTCTGGTCGGCAA---------------------------------------CGGCCTATGGGTTACCGAGAAG------CTTTTCAAACCCGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTC?????????????????????????????
ECHD_Antedon_serrata                     ??????-?????????????????????????????????????????????ATG-CAT--GTCTAAGTAC-AAGCT---TGTACCAAGCG-AAACTGCGGAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-GGAACT-GAGT------TACT------------ACATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---GAACAA--GCGCC---GACTTC------------------------GGGAAGGCGT-----GCTTTTATTAGGAACAAG-GCCAA---TCGGG--CTTG-------------------------------------CCC--GCTCCC---CTTGG-TGAA--CTCTGGATAA-CTTT------GCTGA-TCGCA-----CGGT-CT-------AGC-ACC-GGCGA----CGGATCCTTC-AAATGTCTGCCCTATCA-ACTTTTCGATGGTACGTTATGC-G-CCTACCAT----GGTCT--GCACGGG-TAACGGAGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCTTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGACACAGGGAGGTAGTGA-CGAAAAATAACAATACAGGT--CTCTCT-CG----A-GGCCCTGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGCTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--TGGGCCTAGGTCGCT--------GTCCGCGA---GGTG-TTACTGCCCGTCCT-----------------------------------------------------------------------------GGCCTTT--CTCTCGG-TTTTC-ACCCGGT-GCTCTTAAT-TGAGTGGCGGGGGTGACCGG-----------------------------------------------------------------------------------------AACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGCC----------ATA-CGCCTGAA-TAGCAGAGCATGGAATAATGGAATAGGACCT-TGGT-TCTA-TTGCG---TTGGTTT----TCGGAAC-TC--GAGGTAATGATTAAGAGGGACTGA-C-GGGGG-CATTCG---TAT-TGCGGTGTGAGAGGTGAAATTCTTGGATCGCC-GCAAG--ACGAC-CGACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCC-GACTCGG-AT-CCCGGGCGTTAT-TAC---AAT------GACGCG--GCGGGCAGTC----TACGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGCGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACAGT-AGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTTT-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--GGCTTGCTAAA-TAGT-TGC--GCCACCCGTTGTG----------------------------------------------------------------------------------------------------------------------------------------------------------G-TGGGCGCTT-AACTTCTTAGAGGGACAAG-TGCG-GTT-----------TA-GCCA-CGC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GGC-CACGCGCGC-TACACTGAAAGAATCAG---CGTGTTT-------GCCCTTGGCCG--ACA-GG-TCT--GGGTAATC-CG----TTGA--ACC-TCTTTCGTGCTAGGGAT-AGGGA-CT-TGTAATTATTTCCC-TTCAACGAGGAATGCCCAGTAAGCGCGAGT-CATCAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATCATCGGATCGG-CCGTGTCGGTTTCACCG---------------------------------------------------TTCGCGCGCCG-AAAAGACGCTCAAACTT??-----------?????????????????????-???????????????????????????????????????????
ECHU_Ochetostoma_erythrogrammom          ????CT-GGTTGAT?CTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACT---TTTACACAGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTAAGG-TTCCTT-AGATCG-TACTA-----TCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGA---AAG-CA--CCTCC---GACTGTT----------------------CCGGGAAGAGC-----GTTTTTATTAC-ACCAAA-ACCAAT--CGGTC--CTC--------------------------------------GGGC-CGTCCT---CTTGG-TGA---CTCTGAATAA-CTTTGT----GCTGA-TCGCA-----TGGC-CTC-------GA-GCC-GGCGA----CGTATCTTTC-AAATGTCTGCCCTATCA-ACTTT-CGATGGTACGTGATAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-TG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCG?GCAAATTACCC-ACTCCTGGAACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTC-TTACG----A-GGCCTCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATACGTGATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CTGGTCTCAGGCCGGC?------GTTCG---------------------------------------------------------------------------------------------------CTCGCGGCGAT---------TACTGCCT---------GTCCT--GACCTACCTGCCGGTTCGCCC---------GCA--GA-TGCTCTTGATT-GAGTG-----T--CTGC-GGT--GGCC---GG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGC----------TACA-CAGCTGAA-TATTAGTGCATGGAATAATGGAAGAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAGC-TC--GAGGTAATGATTAAGAGGGACTGA-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCATC-GTAAG--ACCGA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAGTCAAGAACGAAAGTCGGAGGCGAGAACACGATC-AGATACCGT--GGTAGTTCCGACCATAAACGATGCC-AACTAGCGAT-CCGCCGGC-GTT-GTTCT-CAT------GACCCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGGAAACT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTATTAAA-TAGT-TCA--CCTGTTCATGC-------------------------------------------------------------------------------------------------------------------------------------------------------------TGCAGGTGC--AACTTCTTAGAGGGACAAG-TGTA-ATA-----------TA-GACA-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTTGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGTTCCC-----CCTGCTCTG--CAA-AG-AGT--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTATTCCCC-ATGAACGAGGAATTCCCAGTAAGCACGAGT-CATCAGCTCGTGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGACTGAATGGTTTA-GTGAAATCCTCGGATCGG--ACCCGGCTTGGTGGGTTAC------------------------------------CGCCGAGCTGTTGGCGCTGAGAAG----ATGA-TTGAACTTGA-----------TCACTTGGAGGAAGTAAAAGTTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
GAST_Lepidodermella_squammata            ??????-?????????????????????????????????????????????ATG-CAT--GTCTAAGTAC-ACACT---ACGGCAAAGTG-AAACTGCGAAC-GGCTCA-TTA-AATCAG-TTATGG-TTTATT-AGATCG-TGCC------TATC------------ACGTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AAC-TA--GCCCT---GACTT-------------------------ACGGAGGGGC-----GCTTTTATTAG-ATCAAA-ATCAAT--CGGCT--TC---------------------------------------GGC--CGTTTT---TGTGA-TGA---CTCTGGATAA-CTTTT-----GCCGA-CCGCA-----TGGC-CTT-------GG-CCT-GGCGG----CGTATCTTTC-AAATGTCTGCCCTATCA-ACTTT-CGATGGTAGGTGACAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGAGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCGACACGGGGAGGTAGTGA-CGAAAAATAACAATGCTGGG--CTT----C-----A-AGTCCGGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTAGTGG-AGGGCAAGT-CTGGTGACCAGC-AGCC-GCGG-TAATTCCAGC-TCCACGAGCATGTACGTAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CAGGCTTGTGGCCGTG-------GTCCGCTCGATACGGGTGTGCACTGCCGTG----------------------------------------------------------------------CCCGGTCTACGTCTGGTTTACAAC-CTATAGT-GCTCTTAAC-CGGGTGCTATAGGCTGCCACA----------------------------------------------------------------------------------------------AAGTTTACTCTG-AAAAAATTAGAGTGCTTAAAGCAAGCC----------TTG-TGCTTGAA-TACTGTTGCATGGAATAATAGAATAGGACCT-CGGA-TCTA-TTTTG---TTGGTTT----TCGGAGT--C--GAGGTAATGATTAAGAGGGACAGA-C-GGGGG-CATTCG---TAT-TGCGCCGTTAGAGGTGAAATTCTTGGATCGGC-GCAAG--ACGAA-CAACTGCGAA-G-CA---TTTGCCAAGGAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGCC-AACTGCGGAT-CCCGTAGTCTGG-CTTA--AAG------GACTCG--GCGGGCAGC-----TCCGGGAAACCT--AAGTCTATG-GGTTCCGGGGGGAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CA-GGAC-ACCGTTAGGATTGACAGA-CTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGA-CGG--GCGATCCGCTTGCGG------------------------------------------------------------------------------------------------------------------------------------------------------GTCGACTCGATT--TGCTTCTTAGAGGGACAAG-TGGC-GTTCC---------TA-GCCA-CGC-GAAA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACAATGAGGTACGCAG---TGTGCCCG-CAAAG--CCTGATCCG--AAA-GG-ATT--GGGTACAT-------TTAA--ATT-TACCTCGTAATAGGGAT-TGAGC-AT-TGTAACTATTGCTC-ATGAACGAGGAATTCCTAGTAAGCGCGAGT-CATAAGCTTGCGTT-GACTACGTCCCTGCCCTTTGTACACACCGCACCGTCGCTAC-TACCGATTGAATGGTTTA-GCGAGATTCTCGGATTGG-GCCATATTCGCTCGCAA-------------------------------------------GGG--TGAGCATGGTCTGAG--AAGAAACTCAAGCTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTTC---------------------------?
KINO_Pycnophyes_hielensis                ??ACCT-GGTTGATCCTGCCAGTAGTCTTATGCTTGTCTTAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ACGCT---CCGGCAAAGCA-AAACCGCACAA-GGCTCA-TTA-AATCAG-TTAGTA-TTCATT-TGATCA-ATG-------CCTT------------GCATGGA-TAACTG-TGG-CAATTCTAGAGCTAATA-CATGG---ATCCCC--GCACC---GACCT-----------------------CACGGGACGTGC-----GCATTTGTCAG-ACTAAAAACCAAT--CGGCT--CTT-------------------------------------CGG?G-CCGTTC---AGTGG-TGA---ACCATGATAA-CCTCTAC---GCTGA-CCGCA-----CGGT-CTC-------GT-ACC-GG?GG----CCTATCTTTC-GAATGTCTGCCTTATCA-ACTTT-CGATGGTAGATTAAGT-G-CCTACCAT----GGTGA--TAACGGG-TAACGGGGAA-TCA-GGGTT-TG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCACGCAAATTACCC-ACTCCCGGCACGGGGAGGTAGTGA-CAAGAAATAACAATACAGGA--CTCTTT-TG----A-GGCCCTGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGACAAGT-CTGGTG-CCAGC-ACCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAATGCTGCTGCAGTTAAAAAGCTCGTAGTTGGATCT--GGCGTACGGGCTTGCG-------GTCCGCCTTCAGCGTAC-----TGCACGTCCC-----------------------------------------------------------------------GACGTACCTCTCGGCTATCCCT-A---GTT-GCTCTTGAC-TGAGTGACTAGGGTTACCGGA---------------------------------------------------------------------------------------------ATGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGC-----------GAT-CGCT-GAA-TAGTGGTGCATGGAATAATGGAACAAGACCT-CGGT-TCTA-TTTTG---TTGGTTT----CCGGAAC-AC--GAGGTAATGATTAAGAGGGACTGC-T-GGGGT-CATCCG---TAT-TGCTGCGTTAGAGGTGAAATTCTTGGATCGCA-GCAAG--ACGAA-CTACTGCGAAGG-CA---TTTGACAAAAAT--GTTCT-CTTTAGTCAAGAACGAAAGTCGGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCCGACCATAAACGATGCC-GACTGACAAT-CCGCAGGAGTTA-TTAC--AAT------GACTCT--GCGGGCAGCT---TCCCGGGAAACCTT-AAGTTTATG-GGTTCCGGGGGGAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCTGGT-CA-GGAC-ACCGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGTT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--GGCCTACTAAA-TAGT-TCG--TCGATCACGCGTT------------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGCGCC-AACTTCTTAGGGGAACAAG-CAGC-GTT-----------TA-GCGA-TGC-GAAA-TAGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCAGG-GCCGCACGCGCGC-TACACTGAAGGAGGCAA---CGTGTGCTTAC-----CCTGTACCG---GA-AG-AAT--GGGTAACC-CC----ATGA--ATC-CTTTTCGTGCTAGGGAT-TGGGA-AT-TGCAATTATTTCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CACAAGCTCGTGTT-GATTACGTCCCTG?CCTTTGTACACACCGC-CCGTCGCTAC-TACAGATTGAATGATTTA-GTGAGGTCTTTGGACTGG--CTCCTGCGAGGCTGGAA-------------------------------------ACAGTCGCGCCGGTGTGCTGGGAAG-----TTGACCAAACTTGA-----------TTATTTAGATGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCAGAAGGATC----?
MOLL_Biva_Chlamys_islandica              CAACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACT---TTTTGATGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACGA-----TCCT------------ACTTGGA-TAACTG-TGG-CAATTCTAGAGCTAATA-CATGC---AAAAAG--GCACC---GACTCAC-------------------------GGAGGTGC-----GATTTTATCAA-TTCAAA-ACCAAT--CGGTC--GC--------------------------------------AAGGC-CGTCAA---TTTGG-TGA---ATCTGGATAA-CTTTGT----GCTGA-TCGCA-----CGGC-CCTC------GA-GCC-GGCGA----CGTATCTTTC-AAATGTCTGACCTATCA-ACTTT-CGATGGTACGTGCTAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGAGAA-TCA-GGGTT-CG-GTTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGG--CTC-TTTCG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAC-CCT-TTAACGAG-TATCAATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CAGGTCCAGGCTTGCG-------GTCC--------------------------------------------------------------------------------------------------ACTCCTTGGTGGC---------TACTGCTC---------GTCCTG----------ACCTACCTCCCGGTTTTACCCTT---GG-TGCTCTTGATT-GAGTG-------TCTCG-GGT--GGCC---GG---------------------------AACATTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGC----------AATT-CGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TT--GAGGTAATGATTAAGAGGGACAGA-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGATCGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-CCGCCGGA-GTT-GCTTC-AAT------GACTCG--GCGGGCAGCT----TACGGGAAACCA--AAGTTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGT-TCA--CCGATCCGCTCTGC-----------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGTGC--AACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GCCA-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAA---CGTGCTCTTAT-----CCTTGCCCG--GAA-GG-GTT--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTCTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGCTCCTCGGATTGG--TCCCGACACGGGGGGCAA-------------------------------------CCCTCGAGTCGGTGTGCCGAAAAG----ACGA-GCAAACTTGA-----------TTATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCTGTAGGTGAACCTGCAGAAGGATCAAGC?
MOLL_Poly_Acanthopleura_japonica         ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-AGACT---TTCACATAGTG-AAACCGCAAAT-GGCTCA-TTA-AATCAG-TTATGA-TTTCTT-AGATCG-TACAC-----TCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGA---CGT-TC--ACTCC---GACCTTTTT-------------------GCAGGGAAGAGC-----GCTTTTATTAG-ATCAAG-ATCAAT--CGGGC--CTCG-------------------------------------GCC--CGTCCT---GTTGG-TGA---TTCTGAATAA-CTTTGT----GCTGA-TCGCA-----TGGC-CAC-------GC-GCC-GGCGA----CGTATCTTTC-AAGTGTCTGCCCTATCA-ACTTT-CGATGGTACGTGATAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGAGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACAATACGGGAT-CTC-TT-CG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTTCAGGCTGGAG-------GTCC--------------------------------------------------------------------------------------------------GCCTCGCGGCGG---------CTACTTCCC--------GCTCCT--GACCTACCA----TCGGGTTTT-----CCCTT---GG-TGCTCTTGACT-GAGTG-----T--CT-CGGGG--GGCC---AG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGC---------CCCGT-CGCCTGAA-TAATGGTGCATGGAATAATGGAAGAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAG-TC--GAGGTAATGATTAAGAGGGACAGA-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGAA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-CCGCCGGA-GTT-GTTTC-AAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTTTGTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTATTAAA-TAGT-TCG--CCGATCCCTGA-----------------------------------------------------------------------------------------------------------------------------------------------------------TGCGTCGGCGCC-AACTTCTTAGAGGGACAAG-TGGC-GTT-----------TA-GCCA-CAC-GAAA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGAATCAG---CGTGTGTCGTT-----CCTGGCCCG--GAA-GG-GCT--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTCTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCG?GTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGAGCCCCGGATTGG-TCCCGGCATGGGGG?AAC--------------------------------------------CTCCGCCGGTGCGCCGAG--AAGTTGTTCGAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
NEMA_Trichinella_spiralis                ??????-??????????????????AAGCTTGCTTGTCTCAAAGATTAAGCCATG-CAT--GTGTAAGCAC-ACACT--GTTTTAAAAGTG-AAGCCGCGAAT-GGCTCA-TTA-CAACAG-CCACAG-TTTATT-AGAACT-TACA---------A------------TCATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CACGC---ACAAAA--ACTTC---AACTGA----------------------ATTGGTTGAAGT-----GCTTTTATTAG-AACAAAAACCGAA--CGGCG--TTTGACGAATGTTGAA-------------------------CGT--CGAAACTG-TTTGG-TGA---ATCTGAATAA-CTATT-----TCTGA-TCGCA-----TGGT-CT-------AGC-ACC-GGCGA----CATCACTTTC-AAGTGTCTGCCTTATCA-ACCTT-CGATGGTAGCCTATGC-G-ACTACCAT----GGTGA--TAACGGG-TAACGGAGAA-TCA-GGGTT-CG-ACTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCAGCTTGGGGAGGTAGTGA-CGAAAAATAACGAGACGATT--CTCGTT-TG----A-GAAA-CGTTATCGAAATGAGT-ACGCT---TTACAC-ACG-CTAACGAG-TAGCAATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGCTGCGGTTAAAACGCTCGTAGTTGAATTG--TGGTCTTAGACAACA--------GTCCCCCTACAAAGGTGTGGCACGGTTGC-----------------------------------------------------------------------TCGAGATCTTCATTCGTGGTTGC-TGTTGTT-GCTCTTCAT-TGAGTGTCAATGGTGCCTCG-----------------------------------------------------------------------------------------------AGATTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGTT---------GTGA-TGCCTGAA-TAATGGTGCATGGAATAATAGAATACGATCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGAACC--G--GAGATAATGATTGAAAGGAACAGA-C-GGGGG-CATTCG---TAT-TGCTGCGTTAGAGGTGAAATTCTTGGATCGCA-GCAAG--ATGAA-CAATTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACGGTAAACTATGCC-AACCAGCGAT-TCGCCGAAGTTC-ATT---TAA------GACTCG--GCGAGCAGCT----TCCGGGAAACCA--AAGTGTTTC-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGCA---TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGGAAGGATTGACAGA-TTGACAGCTCAGCTCTTTCTTGATTCA-GTGGGT-AGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--ACCCTATTAAA-TAGT-GAC--AGTATTGTATTTTTT----------------------------------------------------------------------------------------------------------------------------------------------------------GTGCTGAT--CACTTCTTAGAGGGAC----TGGC-AAATTGA-------AA-GCTG-CAC-GAAA-AAGAG-CAATAACAGGTCTGTGAT-GCCCTTC-GA-TGTCCGGG-GCTGCACGCGCGC-TACAATGAAAGCGTCAA---CGTGAGTTACGT----CCTTACCTG--AAA-AG-GTT--TGGCAATC-GA----ATGA--AAC-GTTTTCTTGAATGGAAT-AGGGA-AT-TGCAATTGTTTCCC-TTGAACGAGGAATTCCCAGTAAGCGTGAGT-CATTAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACGCC--CGTCGCTAC-TACCGATTGGATGATTTA-GTGAGGTGTTTTGACTGG-CGCCAGTAGTCGGATAT----------------------------------------------GTATTCGTCGCGCCGGG-AAATTT-CCCAAACCAAA-----------TCATCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAAC-TGCGGAAGGATC----?
NEME_Lineus_sp                           ????CT-GGTTGATTCTGCCAGTAA-CATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-GAACT---TTTACACAGTG-AAACCGCGAAT-GGCTCA-TTA-GATCA?-TTATGG-TTCCTT-AGATCG-TCCAA-----TCTT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---TAC-AA--GCTCC---GACCCTCA---------------------CGGGGAAGAGC-----GCTTTTATTAG-GTCAAA-ACCAAT--CGGCA--CTC-------------------------------------------CGTGTCCA-CTTGA-CGA---ATCTGGATAA-CTTTGT----GCGGA-ACGCA-----CGGC-CCT------TGC-GCC-GGCGT----CGTATCTTTC-AAATGTCTGCCCTATCA-AATTT-CGTAGGCCGGTGATAT-G-CCCGCCTA----GTTTC--TTACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTTCTAGCACAGAGAGGTAGTGA-CGAAAAATAACAATACGGGA--CTC-TTTCG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGCTGTTGCAGTTAAAAAGTTCGTAGTTGGATCT--CGGATTTGGGCTAGCG-------GTCCGA-----------------------------------------------------------------------------------------------TGTCTTCGGTT------------TACTGCTA---------GTCTC--GA-CTACCCGCCGGTCTT-CC---------CCT--GG-TGCTCTTAACT-GAGTG-----C--CTCG-GGT--TACC---GG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGCG----------CTC-CGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TC--GAGGTAATGATTAAGAGGGACGGA-C-GGGGG-CATTCG---TAT-TACGGTGTTAGAGGTGAAATTCTAGGATCGCC-GTAAG--ACGGA-CGGCTGCGAAAG-CG---TTTGCCAAGCAC--GTTTT-CTTTAGTCAAGAGCGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CCTAGTTCTGACCATAAACGATGCC-AACTAGCAAT-CCGCCGGA-GTT-GCTTC-AAT------GACTCG--GCGGGCAGCT----TCCGGGAAACCA--AAGTCTTTG-GGTTCC-GGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CC-GGAC-ACTGGAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTATTAAA-TAGT-TCA--CCGATCACGA------------------------------------------------------------------------------------------------------------------------------------------------------------TTCGTCGGTGCC-AACTTCTTAGAGGGACTAG-TGGC-AAAC----------AA-GCCA-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GC-GCACGCGCGC-TACACTGAAGGAATCAA---CGTGCGTCTTC-----CCTGGTCCG--AGA-GG-ATT--GGGTAACC-CG----TTGA--ACC-TCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTATTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATCATCGGATTGG--TCGCGGCGCGTGGGGCAAC-----------------------------------CCTCGTGCCGTTGTCTGCCGAAAAG----ACGA-TCGAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCAGAAGGATCATTA?
NEMM_Gordius_aquaticus                   ????CT-GGTTGAT?CTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTATAAGTAT-AAACT---AACTTAAAGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTTATT-AGATCG-TACA------ACCC------------ACATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---TAAAAA--GTCGA---ATCGC-------------------------GAGGTCCGAC----CGCTTTTATTAG-AACAAA-AACTAA--CGTT----------------------------------------------------------TTTGG-TGA---CTCGGAATAA-CTTTGT----GCCGA-TCGCA-----CGGT-CTC-------GT-ACC-GGCGA----CGTATCTTTC-AAATGTCTGCCTTATCA-ACTGT-CGATGGTAGGTTATGC-G-CCTACCAT----GGTCG--TAACGGG-TAACGGAGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCC-GGCACGGGGAGGTAGTGA-CGATAAATAACAATGCAGGT--CTCTTT--G----A-GACCCTGTAATTGGAATGAGA-TCACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAAAAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTAACGGTGGGAA-------GCCCGCTTAACCGCGAT-CGTTTCCCAGTCC------------------------------------------------------------------------GACCTATTATTCGTCCTCCCCT-C---GAT-GCTCTTTAC-TGAGTGTCTTGGGT--ACGGA---------------------------------------------------------------------------------------------ACTTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGC---------TCGAA-GCCTCGAA-TATCGATGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAA-CC--GAGGTAATGATTAAGAGGAACGGA-C-GGGGG-CATCCG---TAC-TGTGGCGCTAGAGGTGAAATTCTTGGACCGCC-GCAAG--ACGAA-CGACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGGCGATC-AGATACCGC--CGTAGTTCTGACCATAAACGATGCC-GACCGGTAAT-TTACTGTGGATC-TTTT--TAC------GACCCA--GTAAGCGACC----TTCGGGAAACCA--AAGTTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGAAAACT-CACCCGGC-CA-GGAC-ACTGTAAGGATTGACAGA-TTGATAGC-----TCTTTCTCGATTCA-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTCAATTCCGATAACG-AACGAGACTCT--AACCTACTTAC-TAGA-ACG--TCGATCATTTTC-------------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGCGA--AGCTTCTTAGAGGGACAAG-CGAC-GATATTTT------CA-GTCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCTGCACGCGCGC-TACACTGAAAGAATCAG---CGTGTCATTCT-----CCTGGTCCG--AAA-GGATCCT-GGGTAATC-CG----TTGA--AAC-TCTTTCGTGATGGGGAT-AGGGA-AT-TGTAATTATTTTCC-TTGAACGAGGAATT?CTAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTAAGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTTGGACGGG--TCTTGATTCGGGACTTA-----------------------------------------GTTCAGCCATGCGCCTGAAAA-----TTGATCTAGCTCAG-----------TCATTTCGAGGAAGTAAAAGT-CGTAACAAGGTTTCC---------------------------?
PHOR_Phoronis_vancouverensis             ??????-????????????????AGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--ATCTAAGTAC-ACACT---TTCACACGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TACAA-----TCCT------------ACTTGGA-TAACTG-TAG-TAATTCTAGAGCTAATA-CATCG---AAA-CA--ACTCC---GACTCGC------------------------GGGAAGAGC-----GCTTTTATTAG-ATCAAA-ACCAAT--CGGGC--TC--------------------------------------GTCCC-CGTCAC---ATTGG-TGA---CTCTGGATAA-CTTTGG----GCTGA-TCGCA-----TGGC-CTT-------GC-GCC-GGCGA----CGTATCTTTC-AAATGTCTGCCCTATCA-ACTTT-CGATGGTACGTGACAT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACTTCTAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGGCACGGGGAGGTAGTGA-CGAAAAATAACGATACGGGA--CTC-TTTCG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTTTAGGCTAGCG-------GTCC-----------------------------------------------------------------------------------------------------GCCTCGCGCG--------TTACTGCTC---------GTCCT--GACCTACCTCCCGGTTTT-CC---------CTT--GG-TGCTCTTGATT-GAGTG-----T--CTCG-GGT--GGCT---GG---------------------------AACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCG----------ACT-CGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TT--GAGGTAATGATTAATAGGGACGGC-C-GGGGG-CATTGC---TAT-TACGGTGTTAGAGGTGAAATTCTTGGATCGCC-GTAAG--ACGGA-CAGCTGCGAAAC-G----TTTGCCAAGAGC--GTTTT-CATTAGTCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGATACCGT--CCTAGTTCTGACCATAAACGATGCC-AACTGAGCAT-CCGCCGGA-GTT-GCTTC-AAT------GACTCG--GCGAGCAGCT----TCCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCC-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-AGC-GCTTAATTTGACTCAACACGGGAAAGCT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGT-TCA--CCGGTCCC--------------------------------------------------------------------------------------------------------------------------------------------------------------GATGTGCCGGTGCAACTTCTTAGAGG-ACAAG-CGCG-A-------------TA-GCCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGTGCGC-TACACTGAAGGGATCAGG--CGTGCGTCTAC-----CCTGGCCTG--GAA-GG--TT--GGGTAACC-CG----TTGA--ACC-CCCTTCGTGCTAGGGAT-TGGGG-CT-TGTAATTCTTCCCC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCCGGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAACGGTTTA-GTGAGAGCCTCGGATTGG--TCCTGCATGGTGGGCAA--------------------------------------CCATCGCGCCGGTGTGCCGAGAAG-----CTGCTCAAACTTGA-----------TCGTTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGT-------------------------?
PLAC_Trichoplax_adhaerens                ?AACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAT-AAGCA---CTTGTACTGTG-AAACTGCGAAT-GGCTCA-TTA-AATCAG-TTATCG-TTTATT-TGATCG-TACAT-----TACT------------ACATGGA-TAACCG-TGG-TAATTCTAGAGCTAATA-CATGC---GAA-AA--GTCCC---GACTTT-----------------------GCGGAAGGGAT-----GTATTTATTAG-ATCAAA-ACCAA---TGCGG--GCTTG------------------------------------CCC--GGTG-----TTTGG-TGA---TTCATAATAA-CTTA------TCGAA-TCGCA-----TGGC-CTT-------GT-GCC-GGCGA----TGCTTCATTC-AAGTTTCTGCCCTATCA-ACTTT-CGATGGTAAGGTATTG-G-CTTACCAT----GGTTA--CAACGGG-TAACGGAGAA-TTA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGGCAATTACCC-AATCC-GACACGGGGAGGTAGTGA-CAAGAAATAACGATACGGGG--CCATCT-------G-GCTTC-GTAATCGGAATGAGT-ACAAT---TTAAAT-CCT-TTAACGAG-GATCCATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTT--CGGAATGAATCTGACG-------GTCCGCTAAC-GGTGAGTACTGGATGATTTGTT------------------------------------------------------------------------CTTCTT-CTTGAGGGC-----TGCATAT-GCTCTTAAT-TGAGTGTGTGTAGGACTTGAG---------------------------------------------------------------------------------------------ACTTTTACTGTG-AAAAAATTAGAGTGTTCAAAGCAGGC-----------CAT-CGCTTGAA-TACCTGAGCATGGAATAATAAAATAGGACTT-TGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC--C--GAAGTAATGATTAATAGGGACAGT-T-GGGGG-CATTCG---TAC-TTCATTGTCAGAGGTGAAATTCTTGGATTTAT-GAAAG--ACGAA-CAACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGACGATC-AGATACCGT--TGTAGTTCTAACCATAAACGA-GCC-GTCTAGGGAT-CAGTGGGTGTTA-TTT---TAT------GACTCC--ATTGGCACCT----TAAGGGAAACCA--AAGATTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGCCAT-GGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCAGGT-CC-AGAC-ATAGTAAGGATTGACAGA-TTGATAGC-----TCTTTCTTGATTCT-ATGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGTTAACG-AACGAGACCCT--ATCCTACTAAA-TAGT-TAGT-CGTTCTACG----------------------------------------------------------------------------------------------------------------------------------------------------------------GAACACGCG-AACTTCTTAGAGGGACAAT-TGGC-GTT-----------TA-GCCA-AAG-TAA--GTAGGGCCATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCCGCACGCGCGC-TACACTGATGAAGGCAG---AGAGT--------CCTGCTACACTG--GGA-GG-TGC--GGCTAATC-T-----TTCA--AAC-TTCATCGTGCTGGGGAT-AGACC-CT-TGTAATTATTGGTC-TTGAACGAGGAATTCCTAGTAAGCGCACTG-CATCAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGGATGGTTTA-GTGAGGTCTTCGGATTGG-TGATGGCGTGACTTTAC-------------------------------------------GGTTGTGCCAATTATCGAG---AAGTTGATCAAACTTGA-----------TCATCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTC?GTAGGTGAACCTGCAGAAGGATCAA???
PLAT_Acoe_Paratomella_rubra              ??????-GGTTGATCCTGCCAGTAG-CATA?GCTTGTCTCAAAGATTAAGCCATG-CAT--GTTTATGTTC-AGTAC-----AGAACAGCG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TCTTGG-TTTATT-CGATAC-AAA-------CCTT------------ACTTGGA-TAACTG-TGG-TAAC-CTA-AGCTAATA-CATGCC--ATA-----AGGGT---ACATCAT---------------------------TGCCCG-----GCTTTTATTAG-GCATAA-CTGAAG--CGGCG--TCTC--------------------------------------GCC-GAA------CAGGT-TGA---CTCCAAATAA-CTGC-------AAGA-CCGCG----AAGGC-CTT------CGT-GCC-AGCGG----CAAATCGTTC-AAGTGTCTGCCCTATCA-ACTTT-GGACGGTAGTGTACCG-G-ACTACCGT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCTAA-GGAAGGCAGCAGGCGCGCAAATTACCC-AATCCCCGATCGGGGAGGTAGTGA-CGAAAAATAACAATTCGGGA--CTT----------A-CGTTCCGTAATTGGAATGGGC-ACAAC---CCAAAC-AAT-TGTGCGAG-TAACAAGTTG-TGGGCAAGC-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-GCAACTAGCGTATGTGC--GT-GTTGCGGTTAAAAAGCTCGTAGTTGGATCT--GTGTGCA-AGTTCTATCG-----GCTAATTTTAGTCGAGGGAA--------------------------------------------------------------------------------TCCTTGTACTCTTTTCTGCGCC-GTTCCGGTGACCTTCAA-CAGTCGTCGGTTACGGCGTAGG----------------------------------------------------------------------------------------------CAATTTTACTTTG-AAAAAATTAGAGTGTTTAAAGCGGGCG-----------CA-TGCCTGAA-TAACTGAGCATGGGATAATGGAATAAGACCC-GATC-ACTT-GTTCT---TTGGTTC----TTTG-----A--TCGGTAATGATTAATAGGGACAAG-C-GGGGG-CATTTG---TAT-TGCGACGTTAGAGGTGAAATTCTTGGATCGTC-GCAAG--ACAAA-CTACAGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGATTGAAGAGGATC-AGATACCCT--CGTAGTTCTAACCATAAACGATGCC-AACTTGCGAT-CCGCTGAAGTTA-ATG---TAT------GACTTG---CGGGCAGCT----TCCGGTAAACCA--AAGT---TT-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAAACT-CACCAGGT-CC-AGAC-ATTGTAAGGATTGACAGA-CTGAAGT------TCTTTCTCGATTCT-ATGGAT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACCCC--AACCTGCTAAA-TAGT-GGC--TCCCTACGC-------------------------------------------------------------------------------------------------------------------------------------------------------------GTAGGGAGATT--CGCTTCTTAGAGGGACTA--GTGG-CTCTT---------TA-ACCC-CGT-GAAG-TGGGG-TCATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCTGG-GCTGCACGCGCGC-TACACTGGTCGCCATAA---AATGCTATA-------CCTGCGCGCT-ATG-CG-CGT--GGGCAATC-AC-----CTA--ATG-GCAACCGTGATTGGGAT-AGATT-AT-TGCAACTATTGATC-TTGAACGAGGAATTCCTAGTAAGCACGAGT-CATTAGCTCGTGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGGACGCTGAA-GCGAGTTCTATGGAGGGT--TCGAACAACCGCTTCGC-----------------------------------------------GGATGTTTGAGCACG--AAATAGCTCAAGCTTCG-----------ACGTCTAGAGGAAGTAAAAGT-CGTAACAAG??????????????????????????????????
PLAT_Cate_Stenostomum_leucops            ??????-??????????????????????????TTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-AGGCT---TTGGTACAGCG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-CTATAA-TTTATT-AGATTG-TTC-------TCTT------------ACTTGGA-TAACTG-TGG-GAATTCTAGAGCTAATA-CATGC---GCAAAA--GCTCC---GACCT-----------------------TCGGGCAGGAGT-----GCAGTTATTAG-ACCAAA-ACCAGC--CGAGC--TTCG-------------------------------------GCTC-GAACTG---TTTGG-TGA---CTCTGGATAA-CGACGA----GCGGA-TCGCA-----TGGC-CTT-------GT-GCC-GGCGA----CATATCTTTC-AAGTGTCTGACCTATCA-ACTGA-CGATGGTACGTGATAT-G-CCTACCAT----GGTGA--TAACGGG-TAACGGAGAA-TAA-GGGTT-CG-ACTCCGGAG--AGGGAGCCTGAGAAAT-GGCTACCACATCCAA-GGATGGCAGCAGGCGCGCAAATTACCC-ACTCTCAGTACGAGGAGGTAGTGA-CGAAAAATAACAATGCGGGA--CTCT--ATG----A-GGCCTCGCAATTGGAATGAGC-GCACT---TTAAAT-CGT-TCGACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCG--TAATTCCAGC-TCCAATAGCGTATATTAAAGTT?TTGCAGTTAAAAAGCTCGTAGTTGGATCT--GGGGT-TCGGGTCGGTG------GTTTGCCGCTCTC???--?CTGCCGTGCTCGA-----------------------------------------------------------------------CTCTTACT-AGCCGGTGC-GTC-TCTTGGT-GCTCTTCAC-TGAGTGCCACGAGAGCCTGGC---------------------------------------------------------------------------------------------ATGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCG---------CTTG-CGCCTGAA-TAGTGTTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TT--GAGGTAATGATTAAGAGGGACGGT-C-GGGGG-CATTCG---TAT-TTCGGTGTTAGAGGTGAAATTCTTGGATCGCT-GAAAG--ACGGA-CAAATGCGAAAG-CA---TTTGCCAAGAAC--GTCTC-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGACGATC-AGACACCGT--CCTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-CCGCAGTGGTTG-CTATAAACG------GACTCT---CGAGCAGCT----TCCGGGAAACCA--AAGTGTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGGAAACT-CACCCGGT-CC-GGAC-ACCGTAAGGATTGACAGA-TCGAGAGC-----TCTTTCTTGATTCG-GTGGAT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGT-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAC-TAGT-TGC--GCCGTGTTCATTC------------------------------------------------------------------------------------------------------------------------------------------------------------GCGGCTGTA-GACTTCTTAGAGGGACAGA-TGGC-GTT-----------TA-GCCA-TAC-GAAA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACACTGAAGGAGTCAG---CGTGTGCTAT------CCGTGCTCG--GAA-GA-GCT--CGGTAACC-CG----TTGA--AAC-TCCTTCGTGCTTGGGAT-TGTGG-CT-TGTAATTATCGCGC-ATGAACGAGGAATTCCCAGTAAGTGCAAGT-CATCAGCTTGCGCT-GACTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GCAAGGTACTCAGATTGG--TCTCGATCTTGCACGCA--------------------------------------AGTGTGAGATCGACGGTCGAGAAG-----AAGGCCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCC????????????????????????????
PRIA_Priapulus_caudatus                  ????CT-GGTTGATTCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-AGACG---GATACAAAGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCT-TACTA-----TCCT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AATCAG--GCTCC---GACCT-----------------------TACGGGACGAGC-----GCTTTTATTAG-ACCAA--ACCAAT--CGGGT--TTCG--------------------------------------GCC-CGTTCT---TTTGG-TGA---CTCTGGATAA-CCTTGC----GCTGA-TCGCA-----CGGT-CTC-------GC-ACC-GGCGA----CGTATCTTTC-AAATGTCTGCCTTATCA-ACTTT-CGATGGTAGATTATGT-G-CCTACCAT----GGTCG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCACGCAAATTACCC-ATTCCCGGCACGGAGAGGTAGTGA-CGATAAATAACAATACGGGA--CTCTTT-CG----A-GGACCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TTCAATAGCGTATAT-AAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--GGGGCTTAGGCTGGTG-------GTCCATCTAGC--GATG-GTTACTGGCCTGTCCT-------------------------------------------------------------------GGCCTTTACCTCCCGGTCTA---T-CTTTGTT-GCTCTTGAC-TGAGTGACTCGGGTTGCCGGA---------------------------------------------------------------------------------------------ACGTTTACTTTG-AAAAAATTAGAGTGTTCAAAGCAGGC----------TTTT-TGCCTGAA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-AT--GAGGAAATGATTAAGAGGAACAGA-C-GGGGG-CATTCG---TAC-TGCTGCGTTAGAGGTGAAATTCTTGGATCGTA-GCAAG--ACGAA-CAACAGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGTTCGAAGGTGATC-AGATACCGC--CCTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-CCGCCGGAGTTA-CTAC--AAT------GACTTG--GCGGGCAGCT----ACCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAATCT-CACCCGGT-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--GGCCTACTAAA-TAGT-GAG--CCGATTCCGTCG-------------------------------------------------------------------------------------------------------------------------------------------------------------GTCTGGCGG-CACTTCTTAGAGGGACAAG-CGGC-GGC-----------TA-GCCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCTGCACGCGCGC-TACACTGAAGGAATCAG---CGTGCATTTTG-----CCTTGTCTG--GAA-GG-ACT--GGGTAACC-CG----ATGA--ACC-TCCTTCGTGCTAGGGAT-AGGGA-AT-TGCAATTATTTCCC-TTGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGTGTT-GATCACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTCGGACCGG--TCCCGGCGAGAGGGG-------------------------------------AAACCCTCGCATCGGTGTGCTGGGAAG-----ATGACCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
ROTI_Brachionus_plicatilis               ??ACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGTAC-ATACC---TTAGCACGGTG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCCTT-AGATCG-TTCA------TACT------------ACATGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AAA-AA--GCTCC---GACCG-----------------------TATGGGAAGAGC-----GCTTTTATTAG-ACCAAA-ACCAAT--GGGGT--CGCA------------------------------------AGATC-CCTTTG---TATGG-TGA---CTCTGGATAA-CTTTGT----GCTGA-TCGCA-----TGGC-CTA-------GA-GCC-GGCGA----CGTATCTTTC-AAGTGTCTGCCCTATCA-ACTTT-CGATGGTAAGCGATTT-G-CCTACCAT----GGTTG--TAACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCTAC-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTAGAACGGGGAGGTAGTGA-CGAAAAATAACAATACCGGA--CTCAAT--G----A-GGCTCGGTAATTGAAATGAGT-ACAGT---TTAAAA-CCC-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGTACTAGCATGTG-------GTACGCTTTTT--TGCTGTTACTACATGTCTGG----------------------------------------------------------------------TCCTAATCAACCGGTTGG---C-CGTTGAT-GCCCTTTAT-TGGGTGTTTTCGGTAGCCGGT---------------------------------------------------------------------------------------------ACGTTTACTTTG-AGAAAATTAGAGTGCTTAAAGCAGGCC----------TTA-AGCCTGAA-TAATGTTGCATGGAATAATAGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TGTAGAGCATT-GAGGTAATGATTAATAGGGACAGA-C-GGGGG-CATTCG---TAT-TGCGGTGTTAGAGGTGAAATTCTTGGATCGCC-GCAAG--ACGAA-CAACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTGGAGGTTCGAAGACGATT-AGATACCGT--CCTAGTTCCAACCATAAACGATGCC-AACTAGCGAT-TAGCTGCTGTTA-TATT--TAC------GACACA--GCTAGCAGCT----TCCGGGAAACCA--AAGTTTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGCGGCTTAATTTGACTCAACACGGGAAATCT-CACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGT-ACG--TCGATCTTTA---------------------------------------------------------------------------------------------------------------------------------------------------------------GTCGGCGCG-TACTTCTTAGAGGGACAAG-TAGC-GGT-----------AA-GCTA-CAC-GAAA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTTCGGG-GCCGCACGCGCGC-TACACTGAAGGGATAAG---CGTGTTTTT-------CCTGCTCCG--AAA-GG-AGT--GGGCAATC-CGC---TGAA--ACC-C-CTTCGTGATTGGGAT-CGGGG-CT-TGAAATTATTCTCC-GTGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGGTTTA-GTGAGATCTTCGGATTGG--TCCGGAGGTGTCCGCA---------------------------------------AGGTCGCCTCTAGGTGCCGAGAAG-----ATGATCAAACTTGA-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCAGATGGATCAAGC?
SIPU_Phascolosoma_granulatum             ????CT-GGTTGAT?CTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTAAGCAC-AGGCC---TAAACACGGTG-AAGCTGCGAAT-GGCTCA-TTATAAACGG-CTATGA-TTTATT-GGACAA-TACCT-----AGTT------------ACTTGGA-TAACTG-TGG-TAATTCTAGAGCTAATA-CATGC---AAC-AC--GCTCC---GACCCCCG---------------------CGAGGAAGAGC-----GAGTTTATTAG-ATCGAT-ATCAAA--CCAAC--GAGGG--------------------------------GTTCGCC--CCTCAAAG-CTTGG-TGA---ATCTGGATAA-CTTTGG----TCTGA-TCGCA-----CGGC-CCG------TGC-GCC-GGCGA----CGTATCTTGC-AAGTGTCCGCCCTATCA-ACTCG-AGTCGGTAGGCGCCTT-G-CCTACCGA----GGTGA--TTACGGG-TAACGGGGAA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCATGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCTGACACGGGGAGGTAGTGA-CGAAAAATGACAATACGGGA--CTCTT-ACG----A-GGCCCCGTAATTGGAATGAGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-?GCC-GCGG-TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCT--CGGGCGGAGACGGGCG-------GTGCTA------------------------------------------------------------------------------------------------GCTCCCTTGCCGG--------CAACTGCCCCCTC---CGGCCCT---ACCTGCCGGTTCATCCCATC--------------GG-TGCTCTTAACT-GAGTG-----C--CTGG-GGC--GTCC---GG---------------------------GACGTTTACTTTG-AAAAAATTAGAGTGCTCAAGGCAGGC---------TTGGA-CGCCTGTA-TAATGCTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTGA--TTGGTTA----CCGGAAC-AC--GAGGAAATGATTAAGAGGGACTGC-C-GGGGG-CATTCG---TAT-TACGGCGTGAGAGGTGAAATTCTTGGACCGCC-GTAAG--ACGGA-CTACTGCGAAAG-CA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTCAGAGGATCGAAGACGATC-AGATACCGT--CGTAGTTCTGACCATAAACGATGCC-AACTAGCGAT-CGGCGGGC-GTT-GCTCGATAC------GACCTT--GCCGGCAGCT----TCCGGGAAACCA--AAGTCTTTG-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TTC-CCTTAATTTGACTCAACACGGGAAAACT-CACCCGGT-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCA-GTGGGT-GGTGGTGCATGGCCGT-TCGTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCG--AACCTACTAAC-TAGT-AGGA-CCCGTGGCTC--------------------------------------------------------------------------------------------------------------------------------------------------------TGTGCGCGGGGACATG-AACTTCTTAGAGGGACAGG-TGCA-TGG-----------AA-TGCA-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACACTGACAACATCAG---CAGGTGCTCTCA----CCTGGCCCGA-GAG-GGTTTC--GGGAAACC-CT----TTGA--ACC-GTTGTCGTGGCAGGGAT-CGGGG-TT-TGTAATTATTCCCC-GTGAACGAGGAATTCCCAGTAAGCGCGAGT-CACTAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGGAAGGTTTA-GTGAGGCCATTGGATTGG-GCCGCTGCCGGGTGGGCAAC--------------------------------------CACTTGGCTGGCGTGTCTCGAG-AAGAAGG-CCGAACTTGA-----------CTTTCTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA?
TARD_Macrobiotus_hufelandi               ?TACCT-GGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATG-CAT--GTCTCAGTAC-TTGCT---ATAACAAGGCG-AAACCGCGAAT-GGCTCA-TTA-AATCAG-TTATGG-TTCACT-AGATCG-TACC------GTTT------------ACACGGA-TAACTG-TGG-TAAT?CTAGAGCTAATA-CGTGC---AAC-CA--GCTCG---TTTCCTC----------------------GTGAAGCGAGC-----GCAGTTATTAG-AACAAG-ACCAAT--CCGGC--CCTC------------------------------------GGGTC-GGTAA----CTTGG-TGA---CTCTGAATAA-CCGAA-----GCAGA-GCGCA-----TGGT-CTC-------GT-ACC-GGCGC----CAGATCTTTC-AAGTGTCTGACTTATCA-GCTT---GTTGTTAGGTTATGT-T-CCTAACAA----GGCTA--TTACGGG-TGACGGGGTA-TCA-GGGTT-CG-ATTCCGGAG--AGGGAGCCTGAGAAAC-GGCTACCACATCCAA-GGAAGGCAGCAGGCGCGCAAATTACCC-ACTCCCAGCACGGGGAGGTAGTGA-CGAAAAATAACGATGCGAGGG-CTTTAT---------GCTCTCGCAATCGGAATGGGT-ACACT---TTAAAT-CCT-TTAACGAG-GATCTATTGG-AGGGCAAGT-CTGGTG-CCAGC-AGCC-GCG--TAATTCCAGC-TCCAATAGCGTATATTAAAGTTGCTGCGGTTAAAAAGCTCGTAGTTGAATCT--GGGCAGTTGGACGGATG------GTGCG--------------------------------------------------------------------------------------------------GCTTCACAGCG-----------TACTGTCT---------GCTCGG----------CGCCACAAGCCGGCCATGTCTTG---CA-TGCCCTTCACT-GGGTG------T-GCTT-GGCG-ACC----GG--------------------------AACGTTTACTTTG-AAAAAATTAGAGTGCTCAAAGCAGGCG----------TAC-GGCCTGCA-TAATGGTGCATGGAATAATGGAATAGGACCT-CGGT-TCTA-TTTTG---TTGGTTT----TCGGAAC-TC--GAGGTAATGATTAATAGGAACAGA-C-GGGGG-CATTCG---TAT-TGCGGCGTTAGAGGTGAAATTCTTGGATCGTC-GCAAG--ACGAA-CTACTGCGAAAC-GA---TTTGCCAAGAAT--GTTTT-CATTAATCAAGAACGAAAGTTAGAGGTTCGAAGGCGATC-AGATACCGC--CCTAGTTCTAACCATAAACGATGCC-AACCAGCGAT-CCGTCGGTGTTT-ATTT--GAT------GACTCG--ACGGGCAGCT----TCCGGGAAACCA--AAGTGCTTA-GGTTCCGGGGGAAGTATGGTTGCAAAGCT-GAAACTTAAA-GGAATTGAC-GGAAGGG-CAC-CACCAGGAGT-GGAGCC-TGC-GCTTAATTTGACTCAACACGGGAAAACT-TACCCGGC-CC-GGAC-ACTGTAAGGATTGACAGA-TTGAGAGC-----TCTTTCTTGATTCG-GTGGGT-GGTGGTGCATGGCCGT-TCTTAGTT-GGT-GGAGC-GATTTGTCTGGTTAATTCCGATAACG-AACGAGACTCT--AGCCTGCTAAA-TAGC-CAA--CTGATCCGCA------------------------------------------------------------------------------------------------------------------------------------------------------GCGTCAGTTGCTACAAA--AGCTTCTTAGAGGGACAGG-CGGC-GTT-----------TA-GTCG-CAC-GAGA-TTGAG-CAATAACAGGTCTGTGAT-GCCCTTA-GA-TGTCCGGG-GCCGCACGCGCGC-TACACTGAAGGGAGCAA---CGTGCTTAATCA----CCTTGGCCG--GAA----CCT--GGGGAATC-CG----ATTA--AAC-CCCTTCGTGATTGGGAT-TGAGC-TT-TGTAATTATCGCTC-ATGAACGAGGAATTCCCAGTAAGCGCGAGT-CATAAGCTCGCGTT-GATTACGTCCCTGCCCTTTGTACACACCGC-CCGTCGCTAC-TACCGATTGAATGATTTA-GTGAGGTCTTCGGACTGG--CCATCGAGGCTA?C?CAA--------------------------------------GGCGGCTTCGTCTGGTTGGGAAG-----ACGACCAAACTGGC-----------TCATTTAGAGGAAGTAAAAGT-CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATC----?
`
